## Some of the analyses are time consuming.
## For those parts, we ran the following codes and stored the results and provided the links of the stored data in the manuscript 

## Required libraries for the study
library(treeio)
library(ggtree)
library(geiger)
library(ape)
library(phytools)
library(stringr)
library(ggrepel)
library(dplyr)
library(parallel)
library(digest)
library(magrittr)
library(tidyverse)
library(caper)

## Setting working directory to use functions
setwd("/Users/admin/Desktop/nwork/simulation/")
set.seed(23456)


## Functions required to run this script
source( "/Users/admin/Desktop/nwork/Empirical/protein_trees.nhx/function_TM_new.R" )

## Set system computational parameters
cores = detectCores()

## Specifying the number of loops 
run<-100
loop<-1000

# Loaded the data and analysis results generated by Dunn et al. 2018 
# Files and scripts are used from the link  https://github.com/caseywdunn/comparative_expression_2017
# Loaded previously stored data generated using "manuscript_kernel.R"
load("/Users/admin/Desktop/nwork/simulation/manuscript_dunn.RData") 


## To perform our analyses, we considered all trees except trees with negative branchlengths

## Identifying calibrated trees with negative edge lengths
trees_negative <- negative_edgelength(gene_trees_calibrated)

## Removing trees with negative branch length to avoid problem in diagnostic tests using caper
gene_trees_pic1<-gene_trees_pic[-trees_negative]  

# ## Adding internal node heights to the trees
gene_trees_pic1<-mclapply(gene_trees_pic1,tree_height,mc.cores=cores) 

## Identifying trees with atleast one duplication event 
trees_of_interest<-mclapply(gene_trees_pic1,tree_with_duplication, mc.cores = cores)
trees_of_interest<-trees_of_interest[!is.na(trees_of_interest)]    
trees_of_interest<-mclapply(trees_of_interest,tree_height,mc.cores=cores) ## Added node height to the trees

## Identifying trees with strong phylogenetic signals 
## We make a vector to collect calibrated tree index with Blomberg's K > 0.551 (as used by Dunn et al. in their paper)
tree_index <-as.numeric(row.names(tree_summary)[(!(is.na(tree_summary$K)) & (tree_summary$K > 0.551))])
trees_new<- gene_trees_pic[c(tree_index)] 


###################################### Randomization tests on calibrated gene trees collected from Dunn et al.#########################################
############To perform randomization of trait (Tau) on different sets of trees ##################


## Initializing variables
pval_all<-NULL
pval_2082<-NULL
Contrast_tau_randomized_5479<-NULL 
Contrast_tau_randomized_2082<-NULL 

## Running the loop for 100 times
## We chose 100 times to save time but one can use higher value as the trend does not change
for(a in 1:run)
{
  #print(a)
  ## Initializing variable for each tree
  Tau_randomized_tree<-NULL 
  Tau_randomized_filtered_tree<-NULL
  
  ## We aim to shuffle or permute the trait data for 2 different sets of lists of trees
  Tau_randomized_tree<-mclapply(trees_of_interest,shuffling_tau,mc.cores = cores) ## Using list of 5479 trees with atleast one speciation and duplication event
  Tau_randomized_filtered_tree<-mclapply(trees_new,shuffling_tau,mc.cores = cores)  ## Using list of 2082 trees with strong phylogenetic signal

  ## Calculated PIC based on permuted Tau data for both sets of trees
  Tree_pic_randomized<-mclapply(Tau_randomized_tree,contrast_random,mc.cores = cores)
  Filtered_tree_pic_randomized_tau<-mclapply(Tau_randomized_filtered_tree,contrast_random,mc.cores = cores)

  ##Summarizing and combining the data slots of all trees in a single dataframe and removing rows with tip data for which contrasts are not available
  summary_tree_pic_randomized<-bind_rows(lapply(Tree_pic_randomized,summary_function))
  summary_filtered_tree_pic_randomized_tau<-bind_rows(lapply(Filtered_tree_pic_randomized_tau,summary_function))
  Random_tau_contrast<-summary_tree_pic_randomized[which(!is.na(summary_tree_pic_randomized$pic_abs_random)),]
  Random_tau_contrast_filtered_tree<-summary_filtered_tree_pic_randomized_tau[which(!is.na(summary_filtered_tree_pic_randomized_tau$pic_abs_random)),]
  
  ## This step is to remove rows with contrast values higher than 0.5 (if any) as used by Dunn et al.
  Random_tau_contrast<-Random_tau_contrast[which(Random_tau_contrast$pic_abs_random < 0.5),]
  Random_tau_contrast_filtered_tree<-Random_tau_contrast_filtered_tree[which(Random_tau_contrast_filtered_tree$pic_abs_random < 0.5),]

  ## Removing NA Events and collecting nodes contrast 
  nodes_contrast_random<-Random_tau_contrast[!is.na(Random_tau_contrast$D),]
  Contrast_tau_randomized_5479<-rbind(Contrast_tau_randomized_5479,nodes_contrast_random)
  nodes_contrast_random_tau_filtered_tree<-Random_tau_contrast_filtered_tree[!is.na(Random_tau_contrast_filtered_tree$D),]
  Contrast_tau_randomized_2082<-rbind(Contrast_tau_randomized_2082,nodes_contrast_random_tau_filtered_tree)
  
  ##Extracting PICs of speciation and duplication events after ramdomizing Tau for both set of trees before performing Wilcoxon test
  speciation_pic.r <- nodes_contrast_random$pic_abs_random[which(nodes_contrast_random$Event=="Speciation")]
  duplication_pic.r <- nodes_contrast_random$pic_abs_random[which(nodes_contrast_random$Event=="Duplication")]
  speciation_pic.rfilter <- nodes_contrast_random_tau_filtered_tree$pic_abs_random[which(nodes_contrast_random_tau_filtered_tree$Event=="Speciation")]
  duplication_pic.rfilter <- nodes_contrast_random_tau_filtered_tree$pic_abs_random[which(nodes_contrast_random_tau_filtered_tree$Event=="Duplication")]
  
  ## Performing two sided Wilcoxon test 
  wilcox_2_tailed.r <- wilcox.test(duplication_pic.r,speciation_pic.r)$p.value
  wilcox_2_tailed.rfilter <- wilcox.test(duplication_pic.rfilter,speciation_pic.rfilter)$p.value
  
  ## Collecting P values for further use
  pval_all<-append(pval_all,wilcox_2_tailed.r)
  pval_2082<-append(pval_2082,wilcox_2_tailed.rfilter)
}


################## To perform randomization of events ("Speciation"/"Duplication"/"NA") on the same sets of trees ############### 
## Initializing variables
pval_all_events<-NULL
pval_2082_events<-NULL
Contrast_event_randomized_5479<-NULL 
Contrast_event_randomized_2082<-NULL 


## running the loop for 100 times
for(b in 1:run)
{
  #print(b)
  ## Initializing variable for each tree
  Event_randomized_tree<-NULL 
  Event_randomized_filtered_tree<-NULL 
  
  ## Sensitivity of the analysis were tested with randomization method
  ## We aim to shuffle or permute the internal node events for 2 different set of trees
  Event_randomized_tree<-mclapply(trees_of_interest, shuffling_event, mc.cores = cores) ## Using list of 5479 trees with atleast one speciation and duplication event
  Event_randomized_filtered_tree<-mclapply(trees_new,shuffling_event,mc.cores = cores) ## Using list of 2082 trees with strong phylogenetic signal
  
  ##Summarizing and combining the data slots of all trees in a single dataframe and removing rows with tip data for which contrasts are not available
  summary_event_randomized_pic_tree<-bind_rows(lapply(Event_randomized_tree,summary_function))
  summary_filtered_tree_pic_randomized_event<-bind_rows(lapply(Event_randomized_filtered_tree,summary_function))
  Random_event_contrast<-summary_event_randomized_pic_tree[which(!is.na(summary_event_randomized_pic_tree$pic)),]
  Random_event_contrast_filtered_tree<-summary_filtered_tree_pic_randomized_event[which(!is.na(summary_filtered_tree_pic_randomized_event$pic)),]
  
  ## This step is to check and remove rows with contrast values higher than 0.5 (if any) as used by Dunn et al. 
  Random_event_contrast<-Random_event_contrast[which(Random_event_contrast$pic < 0.5),]
  Random_event_contrast_filtered_tree<-Random_event_contrast_filtered_tree[which(Random_event_contrast_filtered_tree$pic < 0.5),]
  
  ## Removing NA Events and collecting nodes contrasts of newly assigned speciation and duplication events
  nodes_contrast_random_events<-Random_event_contrast[!is.na(Random_event_contrast$event_new),]
  Contrast_event_randomized_5479<-rbind(Contrast_event_randomized_5479,nodes_contrast_random_events)
  nodes_contrast_random_event_filtered_tree<-Random_event_contrast_filtered_tree[!is.na(Random_event_contrast_filtered_tree$event_new),]
  Contrast_event_randomized_2082<-rbind(Contrast_event_randomized_2082,nodes_contrast_random_event_filtered_tree)
  
  ##Extracting PICs of newly assigned speciation and duplication events for both set of trees before performing Wilcoxon test
  speciation_pic_revent <-abs(nodes_contrast_random_events$pic[which(nodes_contrast_random_events$event_new=="Speciation")])
  duplication_pic_revent <- abs(nodes_contrast_random_events$pic[which(nodes_contrast_random_events$event_new=="Duplication")])
  speciation_pic_revent_2082 <- abs(nodes_contrast_random_event_filtered_tree$pic[which(nodes_contrast_random_event_filtered_tree$event_new=="Speciation")])
  duplication_pic_revent_2082 <- abs(nodes_contrast_random_event_filtered_tree$pic[which(nodes_contrast_random_event_filtered_tree$event_new=="Duplication")])
  
  ## Performing two sided Wilcoxon test and collecting P values for plotting
  wilcox_2_tailed_revent <- wilcox.test(duplication_pic_revent,speciation_pic_revent)$p.value
  pval_all_events<-append(pval_all_events,wilcox_2_tailed_revent)
  wilcox_2_tailed_revent_2082 <- wilcox.test(duplication_pic_revent_2082,speciation_pic_revent_2082)$p.value
  pval_2082_events<-append(pval_2082_events,wilcox_2_tailed_revent_2082)
}



###################################### required to run diagnostic plots to check for adequate nodes contrast standardization as per BM ##################################

##In this section, we plan to perform diagnostic test before analyzing the result on 8520 gene trees
## This diagnostic test function takes a lot of time, so we ran and saved the data

## To perform the diagnostic tests, we considered all trees except trees with negative branch lengths, and except pure speciation trees (i.e. 5479 trees)
##Running diagnostic plots to return trees with adequately standardized PICs of Tau as per BM
count<-0
standarized_pic_tree_with_dup<-lapply(trees_of_interest, diagnostic_plot_test) ##Using list of 5479 trees
standarized_pic_tree_with_dup_final<-standarized_pic_tree_with_dup[!is.na(standarized_pic_tree_with_dup)] ## Obtained 2545 tree data passing the diagnostic tests

##We also identified BM trees by excluding very old duplication events from diagnostic test analysis
count<-0
standarized_pic_tree_with_dup_excluding_oldest_nodes<-lapply(trees_of_interest, diagnostic_plot_test_excluding_oldest_dup_nodes,370) ##Using list of 5479 trees with nodelimit 370 My
standarized_pic_tree_with_dup_final_new1<-standarized_pic_tree_with_dup_excluding_oldest_nodes[!is.na(standarized_pic_tree_with_dup_excluding_oldest_nodes)] 
standarized_pic_tree_with_dup_final_new<-standarized_pic_tree_with_dup_final_new1[ ! sapply(standarized_pic_tree_with_dup_final_new1, is.null) ]## We obtained 2682 trees passing the diagnostic tests
#save.image("BM_trees_for_tau1.rda")


##To get rid of bias due to calibration of old duplication nodes preceeding ancient speciation event, 
## We kept only trees where all duplication events are more recent than the oldest speciation event
## Hence, we chose trees with root event as "Speciation" 
 root_speciation_tree<-lapply(trees_of_interest,
                      function(tree){
                      gene_data<-tree@data
                      tip_number<-tree@phylo$Nnode+1
                      root_node<-tip_number+1
                      if(gene_data$Event[root_node] %in% "Speciation") {return(tree)}
                      else{return(NA)}})
## Removing trees for which root event is not a speciation event 
root_speciation_tree<-root_speciation_tree[!is.na(root_speciation_tree)] ## Obtained 1263 list of trees

##Running diagnostic plots on these trees to check for adequate contrast standarization of PICs of Tau as per BM
count<-0
standarized_pic_tree_root_speciation<-lapply(root_speciation_tree, diagnostic_plot_test) ## Using diagnostic tests on 1263 trees
standarized_pic_tree_ancient_speciation<-standarized_pic_tree_root_speciation[!is.na(standarized_pic_tree_root_speciation)] #### We obtained 806 trees passing the diagnostic tests 


###################################### Randomization tests on different sets of trees passing diagnostic tests using different criteria#########################################
###################### Performing randomization of trait (Tau) data of tips using 806 trees #########################

## Initializing variables
pval<-NULL
pval_1sided<-NULL
Contrast_tau_randomized<-NULL

## To run the loop for 1000 times
for(i in 1:loop)
{
  print(i)
  Tau_randomized_ancient<-NULL ##Initializing the variable
  
  ##Permuting tau data for each tree
  Tau_randomized_ancient<-mclapply(standarized_pic_tree_ancient_speciation,shuffling_tau,mc.cores = cores) ## Using the list of 806 trees
  
  ## Contrast calculation for each tree with permuted tau and combining the data slots of each tree by only keeping rows with PIC values
  Tau_randomized_ancient_pic<-mclapply(Tau_randomized_ancient,contrast_random,mc.cores = cores)
  summary_ancient_spe_rtau<-bind_rows(lapply(Tau_randomized_ancient_pic,summary_function))
  summary_ancient_spe_rtau1<-summary_ancient_spe_rtau[which(!is.na(summary_ancient_spe_rtau$pic_abs_random)),]
  summary_ancient_spe_rtau1<-summary_ancient_spe_rtau1[which(summary_ancient_spe_rtau1$pic_abs_random < 0.5),]

  ## Removing NA events 
  contrast_spe_rtau<-summary_ancient_spe_rtau1[!is.na(summary_ancient_spe_rtau1$D),] ## Required for plotting
  Contrast_tau_randomized<-rbind(Contrast_tau_randomized,contrast_spe_rtau) 
  
  ##Collecting PICs of of ramdomized Tau of speciation and duplication events 
  spe.rtau<-contrast_spe_rtau$pic_abs_random[which(contrast_spe_rtau$Event=="Speciation")]
  dup.rtau<-contrast_spe_rtau$pic_abs_random[which(contrast_spe_rtau$Event=="Duplication")]
  delta.rtau<-abs((median(dup.rtau)) - median(spe.rtau))
  
  ## Performing two sided and one sided Wilcoxon tests
  test_2sided<-wilcox.test(dup.rtau,spe.rtau)$p.value ##Two sided test
  test_1sided<-wilcox.test(dup.rtau,spe.rtau,alternative = "greater")$p.value ## Tests if the PICs of duplication is greater than PICs of speciation
  
  ##Appending P value for each run
  pval<-append(pval,test_2sided)
  pval_1sided<-append(pval_1sided,test_1sided)
}

##Adjusting the p values of 1000 tests
adjusted_p_tau<-p.adjust(pval,method = "BY") 


######################  Performing randomization of events ("Speciation/duplication/NA") on 806 trees  #########################
## Initializing variables
pval_event<-NULL
pval_event_1sided<-NULL
Contrast_event_randomized<-NULL

## Running the loop for 1000 times
for(j in 1:loop)
{
  print(j)
  
  Tau_randomized_ancient_event<-NULL ##Initializing the variable
  
  ##Permuting node events for each tree
  Tau_randomized_ancient_event<-mclapply(standarized_pic_tree_ancient_speciation,shuffling_event,mc.cores = cores)
  
  ## Summarizing the data
  summary_ancient_spe_revent<-bind_rows(lapply(Tau_randomized_ancient_event,summary_function))
  summary_ancient_spe_revent1<-summary_ancient_spe_revent[which(!is.na(summary_ancient_spe_revent$pic_Tau)),]
  
  ## Removing NA events 
  contrast_spe_revent<-summary_ancient_spe_revent1[!is.na(summary_ancient_spe_revent1$event_new),]
  contrast_spe_revent<-contrast_spe_revent[which((abs(contrast_spe_revent$pic_Tau)) < 0.5),]
  Contrast_event_randomized<-rbind(Contrast_event_randomized,contrast_spe_revent) ##required for plotting
  
  ##Collecting the PICs of newly assigned speciation and duplication events for comparison
  spe.rev<-abs(contrast_spe_revent$pic_Tau[which(contrast_spe_revent$event_new=="Speciation")])
  dup.rev<-abs(contrast_spe_revent$pic_Tau[which(contrast_spe_revent$event_new=="Duplication")])
  
  ## Performing Wilcoxon one sided and two sided tests
  test_event1<-wilcox.test(dup.rev,spe.rev,alternative = "greater")$p.value
  test_event2<-wilcox.test(dup.rev,spe.rev)$p.value
  
  ##Returning p values of 1000 runs
  pval_event<-append(pval_event,test_event2)
  pval_event_1sided<-append(pval_event_1sided,test_event1)
}
##Adjusting the p values of 1000 tests
adjusted_p_event<-p.adjust(pval_event,method = "BY") 


###################### Randomization of trait (Tau) data on 2545 trees #########################

## Initializing variables
pval_2545_296_2sided<-NULL
pval_2545_296_1sided<-NULL


## Performing the test 1000 times
for(i in 1:loop)
{
  print(i)
  Tau_randomized_2545<-NULL ##Initializing the variable
  
  ##Permuting Tau data for each tree
  Tau_randomized_2545<-mclapply(standarized_pic_tree_with_dup_final,shuffling_tau,mc.cores = cores)
  
  ## PIC calculation of randomized Tau and summarizing of the data in a single dataframe
  Tau_randomized_2545_pic<-mclapply(Tau_randomized_2545,contrast_random,mc.cores = cores)
  summary_rtau1_2545<-bind_rows(lapply(Tau_randomized_2545_pic,summary_function))
  summary_rtau_2545<-summary_rtau1_2545[which(!is.na(summary_rtau1_2545$pic_abs_random)),]
  summary_rtau_2545<-summary_rtau_2545[which(summary_rtau_2545$pic_abs_random < 0.5),]
  
  ## Removing NA events 
  contrast_rtau_2545<-summary_rtau_2545[!is.na(summary_rtau_2545$D),] ## Required for plotting
   
  
  ##Collecting speciation and duplication PICs of randomized Tau for comparison
  spe.rtau_2545<-contrast_rtau_2545$pic_abs_random[which(contrast_rtau_2545$Event=="Speciation" & contrast_rtau_2545$node_age <= 296)]
  dup.rtau_2545_296<-contrast_rtau_2545$pic_abs_random[which(contrast_rtau_2545$Event=="Duplication" & contrast_rtau_2545$node_age <= 296)]
 
  ## Performing tests
  test_2sided_2545_296<-wilcox.test(dup.rtau_2545_296,spe.rtau_2545)$p.value ##Two sided test
  test_1sided_2545_296<-wilcox.test(dup.rtau_2545_296,spe.rtau_2545,alternative = "greater")$p.value ##One sided test
  
  
  ##Appending P value on each run
  pval_2545_296_2sided<-append(pval_2545_296_2sided,test_2sided_2545_296)
  pval_2545_296_1sided<-append(pval_2545_296_1sided,test_1sided_2545_296)
}

###################### Randomization of events ("Speciation/duplication/NA") on 2545 trees #########################

## Initializing parameters
pval_2545_296_event_2sided<-NULL
pval_2545_296_event_1sided<-NULL

## Running the loop for 1000 times
for(j in 1:loop)
{
  print(j)
  
  Tau_randomized_2545_event<-NULL ##Initializing the variable
  
  ##Permuting node events for each tree
  Tau_randomized_2545_event<-mclapply(standarized_pic_tree_with_dup_final,shuffling_event,mc.cores = cores)
  
  ## Summarizing the data
  summary_revent1_2545<-bind_rows(lapply(Tau_randomized_2545_event,summary_function))
  summary_revent_2545<-summary_revent1_2545[which(!is.na(summary_revent1_2545$pic_Tau)),]
    
  ## Removing NA events 
  contrast_revent_2545<-summary_revent_2545[!is.na(summary_revent_2545$event_new),]
  contrast_revent_2545<-contrast_revent_2545[which((abs(contrast_revent_2545$pic_Tau)) < 0.5),]
  
  ##Collecting newly assigned speciation and duplication events PIC data for comparison
  spe.rev_2545<-abs(contrast_revent_2545$pic_Tau[which(contrast_revent_2545$event_new=="Speciation" & contrast_revent_2545$node_age <= 296)])
  dup.rev_2545_296<-abs(contrast_revent_2545$pic_Tau[which(contrast_revent_2545$event_new=="Duplication" & contrast_revent_2545$node_age <= 296)])
    
  ## Performing test
  test_2sided_2545_296_event<-wilcox.test(dup.rev_2545_296,spe.rev_2545)$p.value ##Two sided test
  test_1sided_2545_296_event<-wilcox.test(dup.rev_2545_296,spe.rev_2545,alternative = "greater")$p.value ##One sided test
   
  ##Appending p values
  pval_2545_296_event_2sided<-append(pval_2545_296_event_2sided,test_2sided_2545_296_event)
  pval_2545_296_event_1sided<-append(pval_2545_296_event_1sided,test_1sided_2545_296_event)
}


###################### Randomization of trait (Tau) data on BM trees of Dunn et al. #########################

# Collecting BM trees of Dunn et al.
tree_summary$index<-as.numeric(rownames(tree_summary))
genes_pass_BM <- tree_summary$index[tree_summary$dAIC_bm < 2]
BM_trees_model_fit<-gene_trees_calibrated[c(genes_pass_BM)]

## Initializing parameters
pval_BM_Dunn_296_1sided<-NULL
pval_BM_Dunn_296_2sided<-NULL

## Running the loop for 100 times
for(i in 1:run)
{
  print(i)
  Tau_randomized_BM_dunn<-NULL ##Initializing the variable
  
  
  ##Permuting Tau data for each tree
  Tau_randomized_BM_dunn<-mclapply(BM_trees_model_fit,shuffling_tau,mc.cores = cores)
  
  ## Contrast calculation on randomized Tau and summarizing the data
  Tau_randomized_BM_dunn_pic<-mclapply(Tau_randomized_BM_dunn,contrast_random,mc.cores = cores)
  summary_rtau1_BM_dunn<-bind_rows(lapply(Tau_randomized_BM_dunn_pic,summary_function_BM))
  summary_rtau_BM_dunn<-summary_rtau1_BM_dunn[which(!is.na(summary_rtau1_BM_dunn$pic_abs_random)),]
  
  ## Removing NA events 
  contrast_rtau_BM_dunn<-summary_rtau_BM_dunn[!is.na(summary_rtau_BM_dunn$D),] ## Required for plotting
  
  
  ##Extracting the randomized PIC of speciation and duplication with a node age limit of 296 My for comparison
  spe.rtau_BM_dunn<-contrast_rtau_BM_dunn$pic_abs_random[which(contrast_rtau_BM_dunn$Event=="Speciation" )]
  dup.rtau_BM_dunn_296<-contrast_rtau_BM_dunn$pic_abs_random[which(contrast_rtau_BM_dunn$Event=="Duplication" & contrast_rtau_BM_dunn$node_age <= 296)]
 
  ## Performing  Wilcoxon test
  test_2sided_BM_dunn_296<-wilcox.test(dup.rtau_BM_dunn_296,spe.rtau_BM_dunn)$p.value ##Two sided test
  test_1sided_BM_dunn_296<-wilcox.test(dup.rtau_BM_dunn_296,spe.rtau_BM_dunn,alternative = "greater")$p.value ##one sided test
  
  ##Appending P value on each run
  pval_BM_Dunn_296_2sided<-append(pval_BM_Dunn_296_2sided,test_2sided_BM_dunn_296)
  pval_BM_Dunn_296_1sided<-append(pval_BM_Dunn_296_1sided,test_1sided_BM_dunn_296)
}

###################### Randomization of internal node events on BM trees of Dunn et al. #########################

## Initializing parameters
pval_BM_Dunn_296_1sided_event<-NULL
pval_BM_Dunn_296_2sided_event<-NULL

## Running the loop for 100 times
for(i in 1:run)
{
  print(i)
  Event_randomized_BM_dunn<-NULL ##Initializing the variable
  
  ## Computing PIC 
  Contrast_tree_BM_dunn<-mclapply(BM_trees_model_fit,contrast_calc,mc.cores = cores)
  
  ##Permuting internal node events for each tree
  Event_randomized_BM_dunn<-mclapply(Contrast_tree_BM_dunn,shuffling_event,mc.cores = cores)
  
  ## Summarizing the data
  summary_revent1_BM_dunn<-bind_rows(lapply(Event_randomized_BM_dunn,summary_function))
  summary_revent_BM_dunn<-summary_revent1_BM_dunn[which(!is.na(summary_revent1_BM_dunn$pic)),]
  
  ## Removing NA events 
  contrast_revent_BM_dunn<-summary_revent_BM_dunn[!is.na(summary_revent_BM_dunn$event_new),]
  
  ##Collecting newly assigned speciation and duplication contrast data of trees for comparison
  spe.rev_BM_dunn<-abs(contrast_revent_BM_dunn$pic[which(contrast_revent_BM_dunn$event_new=="Speciation")])
  dup.rev_BM_dunn_296<-abs(contrast_revent_BM_dunn$pic[which(contrast_revent_BM_dunn$event_new=="Duplication" & contrast_revent_BM_dunn$node_age <= 296)])
  
  ## Performing Wilcoxon test
  test_2sided_BM_dunn_296_event<-wilcox.test(dup.rev_BM_dunn_296,spe.rev_BM_dunn)$p.value ##Two sided test
  test_1sided_BM_dunn_296_event<-wilcox.test(dup.rev_BM_dunn_296,spe.rev_BM_dunn,alternative = "greater")$p.value ##One sided test
  
  ##Appending P value on each run
  pval_BM_Dunn_296_2sided_event<-append(pval_BM_Dunn_296_2sided_event,test_2sided_BM_dunn_296_event)
  pval_BM_Dunn_296_1sided_event<-append(pval_BM_Dunn_296_1sided_event,test_1sided_BM_dunn_296_event)
}
#save.image("BM_trees_for_tau1.rda")


###################### Diagnostic tests on BM trees of Dunn et al. #########################

# Adding node height before analysis on BM trees of Dunn et al.
BM_trees_model_fit<-mclapply(BM_trees_model_fit,tree_height,mc.cores=cores)

# Diagnostic tests
count<-0
BM_tree_diagnostic_test<-lapply(BM_trees_model_fit, diagnostic_plot_test_excluding_oldest_dup_nodes, 0) ## with no node age limits
BM_tree_diagnostic_test1<-BM_tree_diagnostic_test[!is.na(BM_tree_diagnostic_test)] 
BM_tree_diagnostic_test_final<-BM_tree_diagnostic_test1[ ! sapply(BM_tree_diagnostic_test1, is.null) ]## finally we obtained 2412 tree data passing the diagnostic test
#save.image("BM_trees_for_tau1.rda")
#save.image("Data_TMRR.rda")

